# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberLayer
                                 A QGIS plugin
 Creates empty Vector layer with preset fiber templates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-12
        copyright            : (C) 2025 by Jonah Gallagher
        email                : jonah1810@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FiberLayer class from file FiberLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fiber_layer import FiberLayer
    return FiberLayer(iface)
